#!/usr/bin/env bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${scriptDir}/environment.sh

echo Push ${projectName}...
gcloud docker -- push gcr.io/${gcpProject}/${projectName}:${projectVersion}
echo Deploy ${projectName}...
ls -l ${baseDir}/kubernetes/deploy.yaml
kubectl apply -f ${baseDir}/kubernetes/deploy.yaml
echo Done.
echo
echo Running Pods
echo ------------
kubectl get pod
echo
echo Running Services
echo ----------------
kubectl get service