#!/usr/bin/env bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${scriptDir}/environment.sh

echo Push ${projectName}...
gcloud docker -- push gcr.io/${gcpProject}/${projectName}:${projectVersion}
echo Done.
