#!/usr/bin/env bash

scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. ${scriptDir}/environment.sh

echo Undeploy ${projectName}...
kubectl delete service/${projectName}
kubectl delete deployment/${projectName}
echo Done.
echo
echo Running Pods
echo ------------
kubectl get pod
echo
echo Running Services
echo ----------------
kubectl get service